package com.hotpot.dao;


import com.hotpot.domain.PointsHistory;
import org.springframework.stereotype.Repository;

@Repository
public interface PointsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_history
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_history
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insert(PointsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_history
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insertSelective(PointsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_history
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    PointsHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_history
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKeySelective(PointsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_history
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKey(PointsHistory record);
}