package com.hotpot.dao;


import com.hotpot.domain.Points;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PointsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insert(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insertSelective(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKeySelective(Points record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKey(Points record);

    int insertOrUpdatePoints(Points points);

    List<Points> getPointsByVipInfo(Integer vipId);
}