package com.hotpot.dao;


import com.hotpot.domain.StoreTable;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StoreTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_table
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_table
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insert(StoreTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_table
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insertSelective(StoreTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_table
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    StoreTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_table
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKeySelective(StoreTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_table
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKey(StoreTable record);

    StoreTable getStoreTable(@Param("tableCode")String tableCode,@Param("storeId")Integer storeId);
}