package com.hotpot.dao;


import com.hotpot.domain.VipInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface VipInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_info
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_info
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insert(VipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_info
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int insertSelective(VipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_info
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    VipInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_info
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKeySelective(VipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_info
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    int updateByPrimaryKey(VipInfo record);

    List<VipInfo> getAllVips();

    List<VipInfo> getVipsByStoreId(Integer storeId);

    VipInfo getVipByMobilephone(String mobilephone);
}