package com.hotpot.domain;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.card_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.paper_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer paperPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.actual_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer actualPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.drink_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer drinkPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.food_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer foodPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.queue_up
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer queueUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.settle
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer settle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.vip_id
     *
     * @return the value of order.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.vip_id
     *
     * @param vipId the value for order.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setVipId(Integer vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.store_id
     *
     * @return the value of order.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.store_id
     *
     * @param storeId the value for order.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_type
     *
     * @return the value of order.pay_type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_type
     *
     * @param payType the value for order.pay_type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.card_id
     *
     * @return the value of order.card_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.card_id
     *
     * @param cardId the value for order.card_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.paper_price
     *
     * @return the value of order.paper_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getPaperPrice() {
        return paperPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.paper_price
     *
     * @param paperPrice the value for order.paper_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setPaperPrice(Integer paperPrice) {
        this.paperPrice = paperPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.actual_price
     *
     * @return the value of order.actual_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.actual_price
     *
     * @param actualPrice the value for order.actual_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setActualPrice(Integer actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.drink_price
     *
     * @return the value of order.drink_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getDrinkPrice() {
        return drinkPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.drink_price
     *
     * @param drinkPrice the value for order.drink_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setDrinkPrice(Integer drinkPrice) {
        this.drinkPrice = drinkPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.food_price
     *
     * @return the value of order.food_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getFoodPrice() {
        return foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.food_price
     *
     * @param foodPrice the value for order.food_price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setFoodPrice(Integer foodPrice) {
        this.foodPrice = foodPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.queue_up
     *
     * @return the value of order.queue_up
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getQueueUp() {
        return queueUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.queue_up
     *
     * @param queueUp the value for order.queue_up
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setQueueUp(Integer queueUp) {
        this.queueUp = queueUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.settle
     *
     * @return the value of order.settle
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getSettle() {
        return settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.settle
     *
     * @param settle the value for order.settle
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setSettle(Integer settle) {
        this.settle = settle;
    }
}