package com.hotpot.domain;

public class Owner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.phone
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.mobilephone
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.login_name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.login_password
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.identity
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.email
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.id
     *
     * @return the value of owner.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.id
     *
     * @param id the value for owner.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.name
     *
     * @return the value of owner.name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.name
     *
     * @param name the value for owner.name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.phone
     *
     * @return the value of owner.phone
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.phone
     *
     * @param phone the value for owner.phone
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.mobilephone
     *
     * @return the value of owner.mobilephone
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.mobilephone
     *
     * @param mobilephone the value for owner.mobilephone
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.login_name
     *
     * @return the value of owner.login_name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.login_name
     *
     * @param loginName the value for owner.login_name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.login_password
     *
     * @return the value of owner.login_password
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.login_password
     *
     * @param loginPassword the value for owner.login_password
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.identity
     *
     * @return the value of owner.identity
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.identity
     *
     * @param identity the value for owner.identity
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.email
     *
     * @return the value of owner.email
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.email
     *
     * @param email the value for owner.email
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.create_time
     *
     * @return the value of owner.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.create_time
     *
     * @param createTime the value for owner.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}