package com.hotpot.domain;

public class Points {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points.vip_id
     *
     * @return the value of points.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points.vip_id
     *
     * @param vipId the value for points.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setVipId(Integer vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points.type
     *
     * @return the value of points.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points.type
     *
     * @param type the value for points.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points.balance_points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer balancePoints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points.balance_points
     *
     * @return the value of points.balance_points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getBalancePoints() {
        return balancePoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points.balance_points
     *
     * @param balancePoints the value for points.balance_points
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setBalancePoints(Integer balancePoints) {
        this.balancePoints = balancePoints;
    }
}