package com.hotpot.domain;

public class PointsHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.operate
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Byte operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.points_account
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer pointsAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_history.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.id
     *
     * @return the value of points_history.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.id
     *
     * @param id the value for points_history.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.vip_id
     *
     * @return the value of points_history.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.vip_id
     *
     * @param vipId the value for points_history.vip_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setVipId(Integer vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.operate
     *
     * @return the value of points_history.operate
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Byte getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.operate
     *
     * @param operate the value for points_history.operate
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setOperate(Byte operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.points_account
     *
     * @return the value of points_history.points_account
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getPointsAccount() {
        return pointsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.points_account
     *
     * @param pointsAccount the value for points_history.points_account
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setPointsAccount(Integer pointsAccount) {
        this.pointsAccount = pointsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.store_id
     *
     * @return the value of points_history.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.store_id
     *
     * @param storeId the value for points_history.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.create_time
     *
     * @return the value of points_history.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.create_time
     *
     * @param createTime the value for points_history.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_history.type
     *
     * @return the value of points_history.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_history.type
     *
     * @param type the value for points_history.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }
}