package com.hotpot.domain;

public class PointsGift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_gift.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_gift.cost
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_gift.stock
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_gift.name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_gift.description
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_gift.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer storeId;

    private Long startTime;
    private Long endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_gift.id
     *
     * @return the value of points_gift.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_gift.id
     *
     * @param id the value for points_gift.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_gift.cost
     *
     * @return the value of points_gift.cost
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_gift.cost
     *
     * @param cost the value for points_gift.cost
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_gift.stock
     *
     * @return the value of points_gift.stock
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_gift.stock
     *
     * @param stock the value for points_gift.stock
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_gift.name
     *
     * @return the value of points_gift.name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_gift.name
     *
     * @param name the value for points_gift.name
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_gift.description
     *
     * @return the value of points_gift.description
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_gift.description
     *
     * @param description the value for points_gift.description
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_gift.store_id
     *
     * @return the value of points_gift.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_gift.store_id
     *
     * @param storeId the value for points_gift.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }
}