package com.hotpot.domain;

public class ValueCardHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.card_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.operate
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Byte operate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.account
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_card_history.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.id
     *
     * @return the value of value_card_history.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.id
     *
     * @param id the value for value_card_history.id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.card_id
     *
     * @return the value of value_card_history.card_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.card_id
     *
     * @param cardId the value for value_card_history.card_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.operate
     *
     * @return the value of value_card_history.operate
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Byte getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.operate
     *
     * @param operate the value for value_card_history.operate
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setOperate(Byte operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.type
     *
     * @return the value of value_card_history.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.type
     *
     * @param type the value for value_card_history.type
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.store_id
     *
     * @return the value of value_card_history.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.store_id
     *
     * @param storeId the value for value_card_history.store_id
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.account
     *
     * @return the value of value_card_history.account
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.account
     *
     * @param account the value for value_card_history.account
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setAccount(Integer account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.price
     *
     * @return the value of value_card_history.price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.price
     *
     * @param price the value for value_card_history.price
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_card_history.create_time
     *
     * @return the value of value_card_history.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_card_history.create_time
     *
     * @param createTime the value for value_card_history.create_time
     *
     * @mbggenerated Fri Dec 25 15:10:08 CST 2015
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}